# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TechnologyStudioApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TechnologyStudioApp

#  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  target 'TechnologyStudioApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TechnologyStudioAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TechnologyStudioApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TechnologyStudioApp-tvOS

end
